name: marcelo-bot

on:
  push:
    branches: [ "master" ]
jobs:
  build-node:
    runs-on: ubuntu-latest
    container: node:16
    env:
      name: 'marcelo-bot'
      TOKEN: ${{ secrets.TOKEN }}
    steps:
      - name: Check Node.js version
        run: node --version

      - name: Check npm version
        run: npm --version

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Display environment variables
        run: |
          echo "TOKEN: ${{ env.TOKEN }}"
          echo "CLIENT_ID: ${{ env.CLIENT_ID }}"
          echo "GUILD_ID: ${{ env.GUILD_ID }}"

      - name: Start
        run: npm run start
